// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.RomanNumeralMath
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("roman1")]
        public string Roman1 { get; set; }

        [JsonProperty("roman2")]
        public string Roman2 { get; set; }

        [JsonProperty("roman1_value")]
        public long Roman1Value { get; set; }

        [JsonProperty("roman2_value")]
        public long Roman2Value { get; set; }

        [JsonProperty("operation")]
        public string Operation { get; set; }

        [JsonProperty("result_number")]
        public long ResultNumber { get; set; }

        [JsonProperty("result_roman")]
        public string ResultRoman { get; set; }

        [JsonProperty("equation_numeric")]
        public string EquationNumeric { get; set; }

        [JsonProperty("equation_roman")]
        public string EquationRoman { get; set; }
    }
}
